name: Linting and Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  checks:
    name: Plugin Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Dependencies
      run: composer install

    - name: Run Linter
      run: composer lint

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Setup Tests
      run: composer setup-tests:ci

    - name: Unit Tests
      run: composer test
